server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    propeerties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    show-sql: true
